name: sportify ci/cd

on:
  push:
    branches: ['**'] # Triggers on pushes to all branches
  pull_request:
    branches:
      - main # Triggers on pull requests to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Runs the workflow on the latest Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # Specifies Node.js version
          cache: 'npm' # Enables caching for npm dependencies

      - name: Install Dependencies
        run: npm ci # Installs dependencies cleanly

      - name: Build
        run: npm run build # Builds the project

      - name: Run Tests
        run: npm test # Runs the test suite
